apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-ssh-pod
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: shared-data
      mountPath: /data
  volumes:
  - name: shared-data
    persistentVolumeClaim:
      claimName: my-pvc
  - name: ssh-keys
    secret:
      secretName: ssh-secret
  initContainers:
  - name: copy-ssh-keys
    image: ubuntu
    command: ["/bin/sh", "-c", "cp /root/.ssh /mnt/ssh-keys"]
    volumeMounts:
    - name: ssh-keys
      mountPath: /mnt/ssh-keys
